repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.0 # Use the latest version
    hooks:
      - id: ruff
        args: [--fix, --select, I, --extend-select, F401]
      - id: ruff-format
        files: \.py$
